# Generated by Django 5.1 on 2024-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_task_taskid_task_catid_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
