# Generated by Django 5.1 on 2024-09-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_task_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
