# Generated by Django 5.1 on 2024-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="catId",
            field=models.IntegerField(null=True),
        ),
    ]
