# Generated by Django 5.1 on 2024-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_task_catid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="catId",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
